services:
  nginx:
    image: nginx:1.25
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - django_network
    restart: always

  backend:
    build:
      context: .
    entrypoint: ["/entrypoint.sh"]
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    expose:
      - "8000"
    env_file:
      - .env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings.dev
    depends_on:
      - db
    networks:
      - django_network
    restart: always

  frontend:
    build:
      context: ./web-ui
      dockerfile: Dockerfile
    volumes:
      - ./web-ui:/app
      - /app/node_modules
      - /app/.next
    expose:
      - "3000"
    environment:
      - NODE_ENV=development
    networks:
      - django_network
    restart: always

  migrate:
    profiles: ["migrate"]
    build:
      context: .
    entrypoint: ["/entrypoint.migrate.sh"]
    volumes:
      - .:/app
    env_file:
      - .env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings.dev
    depends_on:
      - db
    networks:
      - django_network

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.dev
    networks:
      - django_network
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data:
  static_volume:

networks:
  django_network:
    driver: bridge
