# Generated by Django 5.2.1 on 2025-07-10 05:05

from django.db import migrations


def create_default_organization(apps, schema_editor):
    """Create a default organization and assign all existing data to it"""
    Organization = apps.get_model('core', 'Organization')
    User = apps.get_model('core', 'User')
    Account = apps.get_model('core', 'Account')
    Contact = apps.get_model('core', 'Contact')
    Lead = apps.get_model('core', 'Lead')
    Opportunity = apps.get_model('core', 'Opportunity')
    Task = apps.get_model('core', 'Task')
    InteractionLog = apps.get_model('core', 'InteractionLog')
    Product = apps.get_model('core', 'Product')
    Quote = apps.get_model('core', 'Quote')
    QuoteLineItem = apps.get_model('core', 'QuoteLineItem')
    
    # Create default organization
    default_org, created = Organization.objects.get_or_create(
        name='Default Organization',
        defaults={'description': 'Default organization for existing data'}
    )
    
    # Assign all existing data to the default organization
    User.objects.filter(organization__isnull=True).update(organization=default_org)
    Account.objects.filter(organization__isnull=True).update(organization=default_org)
    Contact.objects.filter(organization__isnull=True).update(organization=default_org)
    Lead.objects.filter(organization__isnull=True).update(organization=default_org)
    Opportunity.objects.filter(organization__isnull=True).update(organization=default_org)
    Task.objects.filter(organization__isnull=True).update(organization=default_org)
    InteractionLog.objects.filter(organization__isnull=True).update(organization=default_org)
    Product.objects.filter(organization__isnull=True).update(organization=default_org)
    Quote.objects.filter(organization__isnull=True).update(organization=default_org)
    QuoteLineItem.objects.filter(organization__isnull=True).update(organization=default_org)


def reverse_default_organization(apps, schema_editor):
    """Reverse the migration by removing organization assignments"""
    # This could be more complex but for simplicity, we'll just pass
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_organization_alter_lead_email_account_organization_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_organization, reverse_default_organization),
    ]
