import type { Product, Quote, Opportunity, Lead, Task, Interaction } from "@/types"

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Enterprise Software License",
    description: "Annual enterprise software license with full support",
    price: 10000,
    currency: "USD",
    isActive: true,
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    name: "Professional Services",
    description: "Implementation and consulting services",
    price: 150,
    currency: "USD",
    isActive: true,
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "3",
    name: "Training Package",
    description: "Comprehensive training for end users",
    price: 2500,
    currency: "USD",
    isActive: true,
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "4",
    name: "Support Package",
    description: "24/7 premium support package",
    price: 5000,
    currency: "USD",
    isActive: false,
    createdAt: new Date("2024-02-10"),
  },
]

export const mockOpportunities: Opportunity[] = [
  {
    id: "1",
    name: "Acme Corp Implementation",
    company: "Acme Corporation",
    value: 50000,
    stage: "Proposal",
    closeDate: new Date("2024-03-15"),
  },
  {
    id: "2",
    name: "TechStart Upgrade",
    company: "TechStart Inc",
    value: 25000,
    stage: "Negotiation",
    closeDate: new Date("2024-02-28"),
  },
]

export const mockQuotes: Quote[] = [
  {
    id: "1",
    opportunityId: "1",
    title: "Acme Corp - Enterprise Package",
    totalPrice: 17500,
    createdBy: "John Doe",
    createdAt: new Date("2024-01-25"),
    notes: "Initial quote for enterprise implementation",
    status: "sent",
    lineItems: [
      {
        id: "1",
        quoteId: "1",
        product: mockProducts[0],
        quantity: 1,
        unitPrice: 10000,
        totalPrice: 10000,
      },
      {
        id: "2",
        quoteId: "1",
        product: mockProducts[1],
        quantity: 50,
        unitPrice: 150,
        totalPrice: 7500,
      },
    ],
  },
  {
    id: "2",
    opportunityId: "2",
    title: "TechStart - Training & Support",
    totalPrice: 7500,
    createdBy: "Jane Smith",
    createdAt: new Date("2024-02-05"),
    notes: "Training and support package for existing customer",
    status: "draft",
    lineItems: [
      {
        id: "3",
        quoteId: "2",
        product: mockProducts[2],
        quantity: 2,
        unitPrice: 2500,
        totalPrice: 5000,
      },
      {
        id: "4",
        quoteId: "2",
        product: mockProducts[3],
        quantity: 1,
        unitPrice: 2500,
        totalPrice: 2500,
      },
    ],
  },
]

export const mockLeads: Lead[] = [
  {
    id: "1",
    firstName: "Michael",
    lastName: "Chen",
    email: "michael.chen@innovate.com",
    phone: "+1 (555) 234-5678",
    company: "Innovate Solutions",
    title: "CTO",
    source: "website",
    status: "qualified",
    rating: "hot",
    assignedTo: "John Doe",
    createdAt: new Date("2024-01-10"),
    notes: "Interested in enterprise package, budget approved",
  },
  {
    id: "2",
    firstName: "Sarah",
    lastName: "Williams",
    email: "sarah.w@globaltech.com",
    phone: "+1 (555) 345-6789",
    company: "Global Tech Corp",
    title: "VP of Operations",
    source: "referral",
    status: "contacted",
    rating: "warm",
    assignedTo: "Jane Smith",
    createdAt: new Date("2024-01-15"),
    notes: "Referred by existing customer, needs demo",
  },
  {
    id: "3",
    firstName: "David",
    lastName: "Rodriguez",
    email: "d.rodriguez@startup.io",
    company: "StartupXYZ",
    title: "Founder",
    source: "social_media",
    status: "new",
    rating: "cold",
    assignedTo: "John Doe",
    createdAt: new Date("2024-02-01"),
    notes: "LinkedIn connection, early stage startup",
  },
]

export const mockTasks: Task[] = [
  {
    id: "1",
    title: "Follow up with Innovate Solutions",
    description: "Send pricing proposal and schedule demo",
    type: "follow_up",
    priority: "high",
    status: "pending",
    assignedTo: "John Doe",
    relatedTo: {
      type: "lead",
      id: "1",
      name: "Michael Chen - Innovate Solutions",
    },
    dueDate: new Date("2024-02-15"),
    createdAt: new Date("2024-02-10"),
  },
  {
    id: "2",
    title: "Demo call with Global Tech",
    description: "Product demonstration focusing on enterprise features",
    type: "demo",
    priority: "medium",
    status: "in_progress",
    assignedTo: "Jane Smith",
    relatedTo: {
      type: "lead",
      id: "2",
      name: "Sarah Williams - Global Tech Corp",
    },
    dueDate: new Date("2024-02-12"),
    createdAt: new Date("2024-02-08"),
  },
  {
    id: "3",
    title: "Send contract to Acme Corp",
    description: "Final contract review and signature",
    type: "email",
    priority: "urgent",
    status: "completed",
    assignedTo: "John Doe",
    relatedTo: {
      type: "opportunity",
      id: "1",
      name: "Acme Corp Implementation",
    },
    dueDate: new Date("2024-02-05"),
    createdAt: new Date("2024-02-01"),
    completedAt: new Date("2024-02-05"),
  },
]

export const mockInteractions: Interaction[] = [
  {
    id: "1",
    type: "call",
    subject: "Initial discovery call",
    description: "Discussed current challenges and potential solutions. Very interested in our enterprise package.",
    direction: "outbound",
    duration: 45,
    outcome: "Positive - requested proposal",
    relatedTo: {
      type: "lead",
      id: "1",
      name: "Michael Chen - Innovate Solutions",
    },
    createdBy: "John Doe",
    createdAt: new Date("2024-01-12"),
    completedAt: new Date("2024-01-12"),
  },
  {
    id: "2",
    type: "email",
    subject: "Product information request",
    description: "Sent detailed product brochure and pricing information",
    direction: "outbound",
    relatedTo: {
      type: "lead",
      id: "2",
      name: "Sarah Williams - Global Tech Corp",
    },
    createdBy: "Jane Smith",
    createdAt: new Date("2024-01-16"),
  },
  {
    id: "3",
    type: "meeting",
    subject: "Contract negotiation",
    description: "Final contract terms discussion and agreement on pricing",
    direction: "inbound",
    duration: 90,
    outcome: "Contract agreed, moving to signature",
    relatedTo: {
      type: "opportunity",
      id: "1",
      name: "Acme Corp Implementation",
    },
    createdBy: "John Doe",
    createdAt: new Date("2024-02-03"),
    scheduledAt: new Date("2024-02-03"),
    completedAt: new Date("2024-02-03"),
  },
]
